<?php
if (!defined("_GNUBOARD_")) exit; // 개별 페이지 접근 불가

$sql .= ", wr_video_width = '{$row2['wr_video_width']}',
			 wr_sub1 = '".addslashes($row2['wr_sub1'])."',
			 wr_sub2 = '".addslashes($row2['wr_sub2'])."',
			 wr_sub3 = '".addslashes($row2['wr_sub3'])."',
			 wr_sub4 = '".addslashes($row2['wr_sub4'])."',
			 wr_sub5 = '".addslashes($row2['wr_sub5'])."',
			 wr_sub6 = '".addslashes($row2['wr_sub6'])."',
			 wr_sub7 = '".addslashes($row2['wr_sub7'])."',
			 wr_sub8 = '".addslashes($row2['wr_sub8'])."',
			 wr_sub9 = '".addslashes($row2['wr_sub9'])."',
			 wr_sub10 = '".addslashes($row2['wr_sub10'])."',
			 bl_name = '{$row2['bl_name']}',
			 bl_width = '{$row2['bl_width']}',
			 bl_height = '{$row2['bl_height']}',
			 bl_height_mobile = '{$row2['bl_height_mobile']}',
			 bl_parallax = '{$row2['bl_parallax']}',
			 bl_background = '{$row2['bl_background']}',
			 bl_font_color = '{$row2['bl_font_color']}',
			 bl_title = '{$row2['bl_title']}',
			 bl_title_color = '{$row2['bl_title_color']}',
			 bl_title_size = '{$row2['bl_title_size']}',
			 wr_content_color = '{$row2['wr_content_color']}',
			 bl_text_align  = '{$row2['bl_text_align']}',
			 latest_table = '{$row2['latest_table']}',
			 latest_order_option = '{$row2['latest_order_option']}',
			 latest_count = '{$row2['latest_count']}',
			 latest_mobile_count = '{$row2['latest_mobile_count']}',
			 latest_order_cate = '{$row2['latest_order_cate']}',
			 latest_sel_li_id = '{$row2['latest_sel_li_id']}',
			 latest_skin = '{$row2['latest_skin']}',
			 latest_type = '{$row2['latest_type']}',
			 latest_list_style = '{$row2['latest_list_style']}',
			 latest_gall_cols = '{$row2['latest_gall_cols']}',
			 latest_gall_mobile_cols = '{$row2['latest_gall_mobile_cols']}',
			 latest_gall_itemspace = '{$row2['latest_gall_itemspace']}',
			 latest_option = '{$row2['latest_option']}',
			 latest_mobile_option = '{$row2['latest_mobile_option']}',
			 gall_cols_default = '{$row2['gall_cols_default']}',
			 mix_type = '{$row2['mix_type']}' ";